
//DIFFERENT WAYS OF EXPORTING

// 1. DEFAULT EXPORT
// const API = process.env.REACT_APP_BACKEND;
// export default API
// WHILE IMPORTING ANY NAME CAN BE USED AND CURLY BRACES NOT ALLOWED

// 2. NAMED EXPORT
// export const API = process.env.REACT_APP_BACKEND;
// exports.API = process.env.REACT_APP_BACKEND;
// WHILE IMPORTING SAME NAME MUST BE USED CURLY BRACES ARE REQUIRED 

exports.API = process.env.REACT_APP_BACKEND;